# Generated by Django 5.1.3 on 2024-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('writer', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
                ('view_count', models.IntegerField()),
            ],
        ),
    ]
