# Generated by Django 5.1.3 on 2024-11-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managementapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("pwd", models.CharField(max_length=30)),
                ("rdate", models.DateTimeField()),
                ("udate", models.DateTimeField()),
            ],
        ),
    ]
