# Generated by Django 5.1.3 on 2024-11-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managementapp", "0002_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=300)),
                ("writer", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("rdate", models.DateTimeField()),
                ("udate", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("view_count", models.IntegerField()),
            ],
        ),
    ]
