# Generated by Django 5.1.3 on 2024-11-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managementapp", "0004_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.FileField(upload_to=""),
        ),
    ]
