# Generated by Django 5.1.3 on 2024-11-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0007_attendancerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='attached',
        ),
    ]
