# Generated by Django 5.1.3 on 2024-11-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0008_rename_content_comments_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='attached',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
