# Generated by Django 5.1.3 on 2024-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0009_alter_comments_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.TextField(default='unknown@example.com'),
        ),
    ]
