# Generated by Django 5.1.3 on 2024-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0010_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='files',
            field=models.FileField(upload_to='attendance/'),
        ),
    ]
